### ISSUE TITLE
Starting The Sprint

### ISSUE THREAD

**Issue by BrendanBenshoof** [UrDHT/DevelopmentPlan#12]
@UrDHT/owners 
@UrDHT/supporters 

I expect a lot of you are busy and already have plans today, but the next two days are going to be my besting working time for the next week or so.

I want to get the a python UrDHT prototype up and going in the next day or so, and working well enough for basic testing.

The new repo for the python prototype should be up in a few minutes, with a few initial issues you can start on.

here have some general ones:
- [ ] #10 Need something like a website
- [ ] #8 Need a Logo
- [x] #9 Need to upload a reading list @abrosen @brendanbenshoof
- [x] #11 Examining the multi-language availability of websocket
